services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - '27017:27017'

volumes:
    mongodb:
    mongodb_config:
